# Generated by Django 3.2.5 on 2021-07-08 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('info', models.TextField()),
                ('create_time', models.DateField(auto_now_add=True, null=True)),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_strategy.strategytype')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyTradePositionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(null=True)),
                ('code', models.CharField(max_length=16)),
                ('position', models.IntegerField()),
                ('direction', models.IntegerField()),
                ('strategy_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_strategy.strategyinfo')),
            ],
        ),
    ]
