# Generated by Django 3.2.5 on 2021-07-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_strategy', '0002_strategyinfo_strategytradepositionlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategyinfo',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='strategytradepositionlist',
            old_name='strategy_id',
            new_name='strategy',
        ),
    ]
